carts:
  post:
    priceMode:
      - NotBlank
      - Choice:
        choices: [NET_MODE, GROSS_MODE]
    currency:
      - NotBlank
    store:
      - NotBlank
items:
  post:
    sku:
      - NotBlank
    quantity:
      - NotBlank
      - Type:
        type: numeric
  patch:
    sku:
      - NotBlank
    quantity:
      - NotBlank
      - Type:
        type: numeric
