access-tokens:
  post:
    username:
      - NotBlank
      - Email
      - Regex:
          pattern: '/^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/'
    password:
      - NotBlank

refresh-tokens:
  post:
    refresh_token:
    - Required